### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by sbusard** [jadinm/simulacres-dynamic-sheet#24]
The sheet has a lot of white space. It's difficult to have a global view of it, especially on small screens such as tablets, or when displaying several windows side by side on a laptop.

I suggest to integrate a "compact" mode where margins and paddings are reduced, to make the most of the space available. Space can be gained by reducing the size of the upper part of the sheet in particular, or by making it collapsible: stats are not useful at every instant anyway, as most of the tests are handled by the sheet itself.

**Comment by sbusard** [comment]
Hey @jadinm! I can definitely contribute on this issue (too). Any leads on how to attack the implementation? I took a quick look at the CSS, and I guess most of the style (and so the space I'd like to reduce) comes from Bootstrap itself...

**Comment by jadinm** [comment]
Nice idea :)

#### Spacing on smaller screen

For that, the solution would be to use the class attributes of bootstrap https://getbootstrap.com/docs/4.0/utilities/spacing/ (e.g., "m-sm-0" "p-sm-0") and place them on the locations that you feel are appropriate to compact on smaller screens.

On firefox, this is quite easy to test the rendering on small screen to select the appropriate class attributes (see https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) but other browsers have similar solutions

The html inspector will help you to identify the elements that actually cause the spacing and whether it is a padding or a margin

#### Collapsing the stats (and the bio info ?)

The easiest approach would be to add the class attributes of bootstrap shown at https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements.
I think that you will want to apply the class attributes to the first html tag of https://github.com/jadinm/simulacres-dynamic-sheet/blob/main/templates/bio.html and https://github.com/jadinm/simulacres-dynamic-sheet/blob/main/templates/base_stats.html

Also, it would be nice add a button that would only be visible on small screen (see also https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements for that) to toggle the display (for instance with the symbol https://fontawesome.com/icons/bars?style=solid or with an explicit text). Upon click, it would add or remove the class attributes that hides the stats on a small screen.

**Comment by jadinm** [comment]
I made a release (1.8.0) with this compact mode for smaller screens
I tested it on my phone and it should adapt on resizing the window for laptops too

I am closing the issue but feel free to reopen it if you have further suggestions :)

**Comment by sbusard** [comment]
Thank you for the new version! I planned to work on that but I didn't find the time to do it...
