### ISSUE TITLE
Notes in external window

### ISSUE THREAD

**Issue by sbusard** [jadinm/simulacres-dynamic-sheet#25]
The "Notes" tab is really useful to take notes during the session, but it's a pain to constantly switch between notes and other tabs, such as rolls or magic.

I suggest to add a way to open a new browser window from an existing note, including the editor to edit the note.

**Comment by sbusard** [comment]
Hey @jadinm! I can definitely contribute on this issue! Any leads on how to attack it, both in terms of design and implementation?

**Comment by jadinm** [comment]
A solution that might work is to use a popup window (like demonstrated in https://jsbin.com/uqamiz/1/edit?html,js,output) and then allow the new popup and the old page to communicate with Broadcast channels (see https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API).

~~The only potential problem with this solution is the same origin policy. I don't know if the popup will be allowed to read a broadcast channel of the main page. But if it can, then we can use the broadcast channel to send the user input to the main page as the field gets updated.~~

~~So the first step would be to check with a minimal example that this is actually possible.~~
(I have tested it, it works)

Note that this won't work with Safari (https://caniuse.com/broadcastchannel) but, in a later step, external libraries like https://www.npmjs.com/package/broadcast-channel can be used to circumvent that.

**Comment by jadinm** [comment]
As for the GUI side, we could add a button with the symbol https://fontawesome.com/icons/external-link-alt?style=solid in the note header, next to the other button that shows the note.
This requires changing the [note.html](https://github.com/jadinm/simulacres-dynamic-sheet/blob/main/templates/notes.html) file to add the button and [addCustomListener method in note.js](https://github.com/jadinm/simulacres-dynamic-sheet/blob/main/js/notes.js#L34) to add a listener that triggers the window when a note is created

When everything else work, the last step would to use the same kind of editor in the popup window. I use [summernote](https://summernote.org/).
The configuration of a summernote is in https://github.com/jadinm/simulacres-dynamic-sheet/blob/main/js/background.js#L1 and its update listener (that syncs the summernote with the textarea) is in https://github.com/jadinm/simulacres-dynamic-sheet/blob/main/js/background.js#L45.

**Comment by jadinm** [comment]
This last commit should answer the issue

Note that if the main page is lost, the note in the popup window won't be automatically synchronize its content
But you could still manually ctrl+c/ctrl+v if you reopen the page

**Comment by sbusard** [comment]
This is amazing! Thank you!
